#!/bin/bash

apt-get update

apt-get install -y \
  apt-transport-https \
  build-essential \
  ca-certificates \
  curl \
  gettext \
  git \
  httpie \
  jq \
  software-properties-common \
  unzip \
  wget \
  zip \
  nano
