#!/bin/bash
if ! apt-key fingerprint 0EBFCD88 | grep -q 0EBFCD88; then
  curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
fi

if [[ ! -e /etc/apt/sources.list.d/docker.list ]]
then
    echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list

    apt-get update
fi

apt-get install -y docker-ce
groupadd -f docker
usermod -aG docker $SUDO_USER

# Add a new file with the ExecStartPre override:

# sudo mkdir -p /etc/systemd/system/containerd.service.d
# sudo nano /etc/systemd/system/containerd.service.d/override.conf
# Contents of override.conf:

# [Service]
# ExecStartPre=

# Reload the systemctl daemon:

# $ sudo systemctl daemon-reload

# Now you can start Docker successfully (sudo systemctl start docker).
